version: '3.4'

networks:
  kafka-net:
    driver: bridge

services:
  zookeeper-server:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper-server

    networks:
      - kafka-net
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka-server:
    image: 'bitnami/kafka:latest'
    container_name: kafka-server
    links:
      - zookeeper-server:zookeeper-server
    networks:
      - kafka-net
    ports:
      - 9092:9092
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
      - KAFKA_ADVERTISED_HOST_NAME=kafka-server
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper-server

  kafka-publisher:
    build:
      context: .
      target: kafka_publisher
    container_name: kafka-publisher
    links:
      - kafka-server:kafka-server
    networks:
      - kafka-net
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - zookeeper-server
      - kafka-server
